inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

Rails:
  Enabled: true

AllCops:
  Exclude:
    - '.git/**/*'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'public/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 3.1.0
  NewCops: disable

Metrics/AbcSize:
  Max: 20
  AllowedMethods:
    - change
Metrics/ClassLength:
  Max: 100

Metrics/MethodLength:
  CountComments: false
  Max: 10
  AllowedMethods:
    - context
    - it
    - describe
    - let!
    - initialize
    - change
Metrics/BlockLength:
  AllowedMethods: [ 'describe', 'context', 'class_methods', 'let!' ]
Style/NumericLiterals:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Alias:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Layout/LineLength:
  Max: 130
Lint/RescueException:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Lint/Void:
  Enabled: false
Style/GuardClause:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes
